#!/usr/bin/env python
"""
Generated by 'esmerald createproject' using Esmerald 3.2.0.
"""
import os
import sys

from pymongo.mongo_client import MongoClient

from asyncz.stores.mongo import MongoDBStore
from esmerald import Esmerald, Include
from esmerald.contrib.schedulers.asyncz.config import AsynczConfig


def build_path():
    """
    Builds the path of the project and project root.
    """
    SITE_ROOT = os.path.dirname(os.path.realpath(__file__))

    if SITE_ROOT not in sys.path:
        sys.path.append(SITE_ROOT)
        sys.path.append(os.path.join(SITE_ROOT, "apps"))


def get_scheduler_config() -> AsynczConfig:
    """
    Builds the scheduler configuration.
    """
    return AsynczConfig(
        stores={
            "default": MongoDBStore(
                client=MongoClient(
                    connect=False,
                    username="root",
                    password="mongoadmin",
                    authSource="admin",
                )
            )
        },
        tasks={
            "collect_market_data": "accounts.tasks",
            "send_newsletter": "accounts.tasks",
            "scheduler_demo": "accounts.tasks",
        },
    )


def get_application():
    """
    This is optional. The function is only used for organisation purposes.
    """
    build_path()

    app = Esmerald(
        routes=[Include(namespace="scheduler_example.urls")],
        enable_scheduler=True,
        scheduler_config=get_scheduler_config(),
    )
    return app


app = get_application()
