"""
Esmerald settings for scheduler_example project.

Generated by 'esmerald createproject' using Esmerald 3.2.0.
"""

from typing import Optional

from esmerald.conf.enums import EnvironmentType

from ..settings import AppSettings


class DevelopmentAppSettings(AppSettings):
    debug: bool = True
    app_name: str = "My application in development mode."
    title: str = "My scheduler_example"
    environment: Optional[str] = EnvironmentType.DEVELOPMENT
