"""
Esmerald settings for scheduler_example project.

Generated by 'esmerald createproject' using Esmerald 3.2.0.
"""

from typing import Optional

from esmerald.conf.enums import EnvironmentType
from esmerald.conf.global_settings import EsmeraldAPISettings


class AppSettings(EsmeraldAPISettings):
    app_name: str = "My application in production mode."
    title: str = "My scheduler_example"
    environment: Optional[str] = EnvironmentType.PRODUCTION
    secret_key: str = "esmerald-insecure-thg)qt1lb7kp#+#^ua0e9)y@1!f_@029zqq!0@a@2yv9(ai+pt"
